### ISSUE TITLE
Prevent duplicate styles when including same file

### ISSUE THREAD

**Issue by gkiely** [mathisonian/gulp-sass-bulk-import#10]
I would like to include mypage.scss first and then the remaining .scss files in a folder.

@import "pages/mypage";
@import "pages/*";

Currently this will include mypage.scss twice.

**Comment by denisborovikov** [comment]
It doesn't check included files. Just place mypage outside this folder.

**Comment by gkiely** [comment]
It would be nice if it did though right. I'll submit a PR and leave it up to you guys.

**Comment by gkiely** [comment]
PR submitted.

**Comment by mathisonian** [comment]
closed by #17, thanks @gkiely!
