### ISSUE TITLE
invalid concatenated path on Windows 

### ISSUE THREAD

**Issue by shukriadams** [mathisonian/gulp-sass-bulk-import#18]
I'm running on a Windows machine and I get an error 

File to import not found or unreadable

    @import "c:/foo/bar\_module.scss";

This seems to be caused by the process function in index.js

    fs.readdirSync(filename).forEach(function (file) {
        replaceString += process(filename + path.sep + file);
    });

It's easily fixed by forcing "Unix" style path delimiters

    replaceString += process(filename + '/' + file);

which works fine on Windows because Sass can mange Unix paths regardless of OS (unless I am grossly mistaken, which has been known to happen). Is this a viable/sane fix? I'd be happy to write it and do a pull request.

**Comment by mathisonian** [comment]
thanks @shukriadams, make sense to me. 

let's make sure to confirm it works on windows via Sass, and would be happy to accept a PR!

**Comment by mathisonian** [comment]
closed by #19
